### ISSUE TITLE
Fix urllib2.URLError: <urlopen error

### ISSUE THREAD

**Issue by dylantyates** [NathanUrwin/cookiecutter-git#21]
I put in an empty github password and this happened.

```
Traceback (most recent call last):
  File "/var/folders/1b/24l2xs_d4yl6kfk37bmv4z740000gn/T/tmpxBSc3r.py", line 207, in <module>
    main()
  File "/var/folders/1b/24l2xs_d4yl6kfk37bmv4z740000gn/T/tmpxBSc3r.py", line 202, in main
    setup_git_repo()
  File "/var/folders/1b/24l2xs_d4yl6kfk37bmv4z740000gn/T/tmpxBSc3r.py", line 165, in setup_git_repo
    requests.post(create_remote_url, data=data, headers=headers)
  File "/var/folders/1b/24l2xs_d4yl6kfk37bmv4z740000gn/T/tmpxBSc3r.py", line 79, in post
    return cls._request(url, headers, data, log)
  File "/var/folders/1b/24l2xs_d4yl6kfk37bmv4z740000gn/T/tmpxBSc3r.py", line 53, in _request
    response = urlopen(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

**Comment by NathanUrwin** [comment]
Fixed with 4776082 in the `develop` branch. Going to release Version 0.5.0 (Beta) today :+1:
