### ISSUE TITLE
Fix Windows support

### ISSUE THREAD

**Issue by NathanUrwin** [NathanUrwin/cookiecutter-git#42]
```cmd
Password for 'https://NathanUrwin@github.com':
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Password for 'https://NathanUrwin@github.com': No error
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpvrxz271b.py", line 384, in <module>
    main()
  File "C:\Users\user\AppData\Local\Temp\tmpvrxz271b.py", line 379, in main
    PostGenProjectHook().run()
  File "C:\Users\user\AppData\Local\Temp\tmpvrxz271b.py", line 371, in run
    self._git_repo()
  File "C:\Users\user\AppData\Local\Temp\tmpvrxz271b.py", line 328, in _git_repo
    self._git_push()
  File "C:\Users\user\AppData\Local\Temp\tmpvrxz271b.py", line 265, in _git_push
    watchers=watchers,
  File "c:\python37\lib\site-packages\invoke\__init__.py", line 49, in run
    return Context().run(command, **kwargs)
  File "c:\python37\lib\site-packages\invoke\context.py", line 94, in run
    return self._run(runner, command, **kwargs)
  File "c:\python37\lib\site-packages\invoke\context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "c:\python37\lib\site-packages\invoke\runners.py", line 271, in run
    return self._run_body(command, **kwargs)
  File "c:\python37\lib\site-packages\invoke\runners.py", line 404, in _run_body
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'git push --set-upstream origin master'

Exit code: 128

Stdout: already printed

Stderr: already printed


ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

**Comment by NathanUrwin** [comment]
The new Invoke Responder API was used to help solve #18. This appears to be an Invoke bug, so I've opened an issue there. You can follow it [here](https://github.com/pyinvoke/invoke/issues/561).

**Comment by NathanUrwin** [comment]
See [v0.6.1](https://github.com/NathanUrwin/cookiecutter-git/releases/tag/v0.6.1). I removed the Responder from the hook. Now it temporarily sets the remote origin to URL encoded basic auth. After pushing the initial commit the hooks strips the password from the remote origin git config.
