### ISSUE TITLE
Fix commit GPG signing on Windows

### ISSUE THREAD

**Issue by NathanUrwin** [NathanUrwin/cookiecutter-git#43]
```powershell
gpg: cannot open tty `no tty': No such file or directory
error: gpg failed to sign the data
fatal: failed to write commit object
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpw7r37qjr.py", line 429, in <module>
    main()
  File "C:\Users\user\AppData\Local\Temp\tmpw7r37qjr.py", line 424, in main
    PostGenProjectHook().run()
  File "C:\Users\user\AppData\Local\Temp\tmpw7r37qjr.py", line 416, in run
    self._git_repo()
  File "C:\Users\user\AppData\Local\Temp\tmpw7r37qjr.py", line 368, in _git_repo
    self.git_commit()
  File "C:\Users\user\AppData\Local\Temp\tmpw7r37qjr.py", line 220, in git_commit
    run("git commit --message {}".format(quote(message)))
  File "c:\python37\lib\site-packages\invoke\__init__.py", line 40, in run
    return Context().run(command, **kwargs)
  File "c:\python37\lib\site-packages\invoke\context.py", line 93, in run
    return self._run(runner, command, **kwargs)
  File "c:\python37\lib\site-packages\invoke\context.py", line 100, in _run
    return runner.run(command, **kwargs)
  File "c:\python37\lib\site-packages\invoke\runners.py", line 268, in run
    return self._run_body(command, **kwargs)
  File "c:\python37\lib\site-packages\invoke\runners.py", line 401, in _run_body
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'git commit --message ^"Initial commit^"'

Exit code: 128

Stdout: already printed

Stderr: already printed


ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

**Comment by NathanUrwin** [comment]
Same [Invoke Windows pty issue](https://github.com/pyinvoke/invoke/issues/561) like #34 and #42 but made into separate issues since the hot fixes are downstream work-a-rounds instead of an upstream fix.

**Comment by NathanUrwin** [comment]
Check for `gpg-agent`? Currently disables commit signing temporarily for the initial commit.
